name: GitHub Stats Card & Top Langs Card Update

on:
  schedule:
    # 每天凌晨（UTC时间）运行一次
    - cron: '0 0 * * *'
  # 允许在 Actions 标签页手动触发
  workflow_dispatch:

jobs:
  update-cards:
    name: Update Stats Cards
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予 GITHUB_TOKEN 写权限

    steps:
      # 步骤1：检出你的仓库代码
      - uses: actions/checkout@v3

      # 步骤2：使用正确的 Action 生成统计卡片
      - name: Generate and Commit Stats Cards
        uses: rickstaa/action-readme-stats@v1 # <-- 使用这个正确的 Action
        with:
          # --- 必要参数 ---
          USERNAME: ${{ github.repository_owner }} # 自动获取仓库所有者作为用户名

          # --- 卡片开关 ---
          # 确保这两种卡片都被生成
          STATS_CARD_NEEDED: true
          LANG_CARD_NEEDED: true

          # --- 自定义选项 (和 URL 参数类似) ---
          # 统计卡片自定义
          STATS_CARD_THEME: dracula
          STATS_CARD_SHOW_ICONS: true
          # 语言卡片自定义
          LANG_CARD_LAYOUT: compact
          LANG_CARD_THEME: radical
          
          # --- 提交设置 ---
          # Action 会自动处理提交，无需手动 commit
          COMMIT_MESSAGE: "chore: update readme stats"
          COMMIT_USER: "GitHub Actions"
          COMMIT_EMAIL: "actions@github.com"
          
          # --- 输出路径 ---
          # 定义生成的 SVG 文件存放的位置和名称
          STATS_CARD_PATH: 'generated/stats.svg'
          LANG_CARD_PATH: 'generated/top-langs.svg'

