# .github/workflows/metrics.yml
# (文件名可以自定义，比如 metrics.yml)

name: Metrics Readme Card Update

on:
  # 每天运行一次
  schedule:
    - cron: '0 0 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须要有写权限来提交生成的图片

    steps:
      - name: Generate metrics card
        uses: lowlighter/metrics@latest # <-- 使用这个 Action
        with:
          # 你的 GitHub 用户名
          user: ${{ github.repository_owner }}

          # 要使用的 Token， GITHUB_TOKEN 是最安全的
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # 仓库的 Token，用于分析 stargazers 等，也是用 GITHUB_TOKEN
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # 输出文件的路径和名称
          # 我们生成一张图片，包含所有信息
          filename: generated/metrics.svg

          # ----------- 自定义配置 -----------
          # 基础设置
          base: header, activity, community, repositories, metadata
          
          # 要启用的插件
          # 每个插件都有丰富的自定义选项
          plugin_lines: yes               # 显示代码行数统计
          plugin_languages: yes           # 显示最常用的语言
          plugin_languages_details: bytes-size, percentage # 语言统计的维度
          plugin_languages_limit: 8       # 最多显示 8 种语言
          
          # 主题和布局
          config_timezone: Asia/Shanghai  # 设置时区，例如中国上海
